import type { QuestDef } from './types';
import { QUEST_TITLES } from './quest_ids';

const MS_PER_TICK = 1000 / 60;

function msToTick(ms: number): number {
  return Math.round(ms / MS_PER_TICK);
}

export const QUESTS: QuestDef[] = [
  {
    id: 'nagolipoli',
    title: QUEST_TITLES.nagolipoli,
    description: 'Survive waves of enemies attacking from all directions.',
    objectives: [{ type: 'survive', durationTicks: msToTick(35000) }],
    timeline: [
      { atTick: msToTick(2000), type: 'spawn', creatureKind: 'tank', count: 8, pattern: 'ring', radius: 14 },
      { atTick: msToTick(8000), type: 'spawn', creatureKind: 'tank', count: 12, pattern: 'ring', radius: 14 },
      { atTick: msToTick(13000), type: 'spawn', creatureKind: 'grunt', count: 1 },
      { atTick: msToTick(13800), type: 'spawn', creatureKind: 'grunt', count: 2 },
      { atTick: msToTick(14600), type: 'spawn', creatureKind: 'grunt', count: 2 },
      { atTick: msToTick(15400), type: 'spawn', creatureKind: 'grunt', count: 3 },
      { atTick: msToTick(16200), type: 'spawn', creatureKind: 'grunt', count: 3 },
      { atTick: msToTick(17000), type: 'spawn', creatureKind: 'grunt', count: 4 },
      { atTick: msToTick(17800), type: 'spawn', creatureKind: 'grunt', count: 4 },
      { atTick: msToTick(18600), type: 'spawn', creatureKind: 'grunt', count: 5 },
      { atTick: msToTick(19400), type: 'spawn', creatureKind: 'grunt', count: 6 },
      { atTick: msToTick(25000), type: 'spawn', creatureKind: 'runner', count: 6 },
      { atTick: msToTick(27000), type: 'spawn', creatureKind: 'runner', count: 6 },
      { atTick: msToTick(28500), type: 'message', text: 'Final wave incoming!' },
      { atTick: msToTick(28500), type: 'spawn', creatureKind: 'grunt', count: 8 },
      { atTick: msToTick(28500), type: 'spawn', creatureKind: 'grunt', count: 8 },
    ],
  },
  {
    id: 'monster_blues',
    title: QUEST_TITLES.monster_blues,
    description: 'Blue creatures attack from multiple sides.',
    objectives: [{ type: 'survive', durationTicks: msToTick(20000) }],
    timeline: [
      { atTick: msToTick(500), type: 'spawn', creatureKind: 'runner', count: 10 },
      { atTick: msToTick(7500), type: 'spawn', creatureKind: 'tank', count: 10 },
      { atTick: msToTick(17500), type: 'spawn', creatureKind: 'grunt', count: 12 },
      { atTick: msToTick(17500), type: 'spawn', creatureKind: 'grunt', count: 12 },
    ],
  },
  {
    id: 'the_gathering',
    title: QUEST_TITLES.the_gathering,
    description: 'Enemies gather at strategic positions.',
    objectives: [{ type: 'survive', durationTicks: msToTick(18000) }],
    timeline: [
      { atTick: msToTick(500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(9500), type: 'spawn', creatureKind: 'runner', count: 2 },
      { atTick: msToTick(15500), type: 'spawn', creatureKind: 'tank', count: 2 },
      { atTick: msToTick(24500), type: 'spawn', creatureKind: 'tank', count: 2 },
      { atTick: msToTick(30500), type: 'spawn', creatureKind: 'grunt', count: 2 },
      { atTick: msToTick(39500), type: 'spawn', creatureKind: 'grunt', count: 2 },
      { atTick: msToTick(54500), type: 'spawn', creatureKind: 'runner', count: 2 },
      { atTick: msToTick(54500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(54500), type: 'spawn', creatureKind: 'runner', count: 2 },
      { atTick: msToTick(54500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(57000), type: 'spawn', creatureKind: 'runner', count: 6 },
      { atTick: msToTick(62000), type: 'spawn', creatureKind: 'runner', count: 4 },
      { atTick: msToTick(69000), type: 'spawn', creatureKind: 'runner', count: 2 },
    ],
  },
  {
    id: 'army_of_three',
    title: QUEST_TITLES.army_of_three,
    description: 'Three enemy types attack in sequence.',
    objectives: [{ type: 'survive', durationTicks: msToTick(15000) }],
    timeline: [
      { atTick: msToTick(500), type: 'spawn', creatureKind: 'tank', count: 1 },
      { atTick: msToTick(5500), type: 'spawn', creatureKind: 'tank', count: 1 },
      { atTick: msToTick(15000), type: 'spawn', creatureKind: 'tank', count: 1 },
      { atTick: msToTick(19500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(22500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(26500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(35500), type: 'spawn', creatureKind: 'grunt', count: 1 },
      { atTick: msToTick(39500), type: 'spawn', creatureKind: 'grunt', count: 1 },
      { atTick: msToTick(42500), type: 'spawn', creatureKind: 'grunt', count: 1 },
      { atTick: msToTick(52500), type: 'spawn', creatureKind: 'tank', count: 3 },
      { atTick: msToTick(56500), type: 'spawn', creatureKind: 'runner', count: 3 },
    ],
  },
  {
    id: 'knee_deep_in_the_dead',
    title: QUEST_TITLES.knee_deep_in_the_dead,
    description: 'Wave-based zombie assault.',
    objectives: [{ type: 'survive', durationTicks: msToTick(97000) }],
    timeline: [
      { atTick: msToTick(100), type: 'spawn', creatureKind: 'tank', count: 1 },
      { atTick: msToTick(500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(1500), type: 'spawn', creatureKind: 'runner', count: 2 },
      { atTick: msToTick(2500), type: 'spawn', creatureKind: 'runner', count: 2 },
      { atTick: msToTick(3500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(4500), type: 'spawn', creatureKind: 'runner', count: 2 },
      { atTick: msToTick(5500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(6500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(7500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(8500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(9500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(10500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(11500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(12500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(13500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(14500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(15500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(16500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(17500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(18500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(19500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(20500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(21500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(22500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(23500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(24500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(25500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(26500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(27500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(28500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(29500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(30500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(31500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(32500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(33500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(34500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(35500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(36500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(37500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(38500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(39500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(40500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(41500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(42500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(43500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(44500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(45500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(46500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(47500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(48500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(49500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(50500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(51500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(52500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(53500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(54500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(55500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(56500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(57500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(58500), type: 'spawn', creatureKind: 'runner', count: 1 },
      { atTick: msToTick(59500), type: 'spawn', creatureKind: 'runner', count: 1 },
    ],
  },
];

export const DEFAULT_QUEST_ID = QUESTS[0]?.id ?? 'nagolipoli';

const QUESTS_BY_ID = new Map<string, QuestDef>(QUESTS.map((quest) => [quest.id, quest]));

export function getQuestDef(id: string): QuestDef {
  return QUESTS_BY_ID.get(id) ?? QUESTS[0];
}

export type { QuestDef, QuestId, QuestObjective, QuestStatus, QuestTimelineEvent } from './types';
