export const QUEST_IDS = [
  'fallback',
  'nagolipoli',
  'monster_blues',
  'the_gathering',
  'army_of_three',
  'knee_deep_in_the_dead',
  'the_gang_wars',
  'the_fortress',
  'cross_fire',
  'the_beating',
  'the_spanking_of_the_dead',
  'hidden_evil',
  'land_hostile',
  'minor_alien_breach',
  'alien_squads',
  'zombie_masters',
  '8_legged_terror',
  'ghost_patrols',
  'the_random_factor',
  'spider_wave_syndrome',
  'nesting_grounds',
  'alien_dens',
  'arachnoid_farm',
  'gauntlet',
  'syntax_terror',
  'spider_spawns',
  'two_fronts',
  'survival_of_the_fastest',
  'spideroids',
  'evil_zombies_at_large',
  'everred_pastures',
  'lizard_kings',
  'sweep_stakes',
  'deja_vu',
  'target_practice',
  'major_alien_breach',
  'land_of_lizards',
  'the_lizquidation',
  'zombie_time',
  'frontline_assault',
  'the_collaboration',
  'the_blighting',
  'the_annihilation',
  'the_massacre',
  'the_killing',
  'lizard_zombie_pact',
  'lizard_raze',
  'surrounded_by_reptiles',
  'the_unblitzkrieg',
  'the_end_of_all',
  'spiders_inc',
] as const;

export type QuestId = typeof QUEST_IDS[number];

export const QUEST_TITLES: Record<QuestId, string> = {
  'fallback': 'Fallback',
  'nagolipoli': 'Nagolipoli',
  'monster_blues': 'Monster Blues',
  'the_gathering': 'The Gathering',
  'army_of_three': 'Army Of Three',
  'knee_deep_in_the_dead': 'Knee Deep In The Dead',
  'the_gang_wars': 'The Gang Wars',
  'the_fortress': 'The Fortress',
  'cross_fire': 'Cross Fire',
  'the_beating': 'The Beating',
  'the_spanking_of_the_dead': 'The Spanking Of The Dead',
  'hidden_evil': 'Hidden Evil',
  'land_hostile': 'Land Hostile',
  'minor_alien_breach': 'Minor Alien Breach',
  'alien_squads': 'Alien Squads',
  'zombie_masters': 'Zombie Masters',
  '8_legged_terror': '8 Legged Terror',
  'ghost_patrols': 'Ghost Patrols',
  'the_random_factor': 'The Random Factor',
  'spider_wave_syndrome': 'Spider Wave Syndrome',
  'nesting_grounds': 'Nesting Grounds',
  'alien_dens': 'Alien Dens',
  'arachnoid_farm': 'Arachnoid Farm',
  'gauntlet': 'Gauntlet',
  'syntax_terror': 'Syntax Terror',
  'spider_spawns': 'Spider Spawns',
  'two_fronts': 'Two Fronts',
  'survival_of_the_fastest': 'Survival Of The Fastest',
  'spideroids': 'Spideroids',
  'evil_zombies_at_large': 'Evil Zombies At Large',
  'everred_pastures': 'Everred Pastures',
  'lizard_kings': 'Lizard Kings',
  'sweep_stakes': 'Sweep Stakes',
  'deja_vu': 'Deja Vu',
  'target_practice': 'Target Practice',
  'major_alien_breach': 'Major Alien Breach',
  'land_of_lizards': 'Land Of Lizards',
  'the_lizquidation': 'The Lizquidation',
  'zombie_time': 'Zombie Time',
  'frontline_assault': 'Frontline Assault',
  'the_collaboration': 'The Collaboration',
  'the_blighting': 'The Blighting',
  'the_annihilation': 'The Annihilation',
  'the_massacre': 'The Massacre',
  'the_killing': 'The Killing',
  'lizard_zombie_pact': 'Lizard Zombie Pact',
  'lizard_raze': 'Lizard Raze',
  'surrounded_by_reptiles': 'Surrounded By Reptiles',
  'the_unblitzkrieg': 'The Unblitzkrieg',
  'the_end_of_all': 'The End Of All',
  'spiders_inc': 'Spiders Inc',
};

export function getQuestTitle(id: QuestId): string {
  return QUEST_TITLES[id] ?? id;
}
