import type { BonusId } from './bonuses';
import type { WeaponId } from './weapons';

export type AtlasSheet = {
  key: string;
  path: string;
  frameWidth: number;
  frameHeight: number;
  labels?: Record<string, number>;
};

export const ATLAS_SHEETS: AtlasSheet[] = [
  {
    key: 'game-projs-grid4',
    path: 'assets/crimson/game/projs.png',
    frameWidth: 32,
    frameHeight: 32,
    labels: {
      pistol: 0,
      assault_rifle: 0,
      shotgun: 1,
      sawed_off_shotgun: 1,
      submachine_gun: 2,
      gauss_gun: 0,
      mean_minigun: 0,
      flamethrower: 2,
      plasma_rifle: 0,
      multi_plasma: 0,
      plasma_minigun: 0,
      rocket_launcher: 1,
      seeker_rockets: 1,
      plasma_shotgun: 0,
      blow_torch: 2,
      hr_flamer: 2,
      mini_rocket_swarmers: 1,
      rocket_minigun: 1,
      pulse_gun: 0,
      jackhammer: 1,
      ion_rifle: 0,
      ion_minigun: 0,
      ion_cannon: 0,
      shrinkifier_5k: 0,
      blade_gun: 0,
      spider_plasma: 0,
      evil_scythe: 0,
      plasma_cannon: 0,
      splitter_gun: 0,
      gauss_shotgun: 0,
      ion_shotgun: 1,
      flameburst: 0,
      raygun: 0,
      unknown_34: 0,
      unknown_35: 0,
      unknown_36: 0,
      unknown_37: 0,
      unknown_38: 0,
      unknown_39: 0,
      unknown_40: 0,
      plague_sphreader_gun: 0,
      bubblegun: 0,
      rainbow_gun: 0,
      grim_weapon: 0,
      fire_bullets: 0,
      unknown_46: 0,
      unknown_47: 0,
      unknown_48: 0,
      unknown_49: 0,
      transmutator: 0,
      blaster_r_300: 0,
      lighting_rifle: 0,
      nuke_launcher: 0,
    },
  },
  {
    key: 'game-projs-grid2',
    path: 'assets/crimson/game/projs.png',
    frameWidth: 64,
    frameHeight: 64,
  },
  {
    key: 'game-particles-grid8',
    path: 'assets/crimson/game/particles.png',
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: 'game-particles-grid4',
    path: 'assets/crimson/game/particles.png',
    frameWidth: 64,
    frameHeight: 64,
  },
  {
    key: 'game-bonuses-grid4',
    path: 'assets/crimson/game/bonuses.png',
    frameWidth: 32,
    frameHeight: 32,
    labels: {
      points: 12,
      energizer: 10,
      weapon: 1,
      weapon_power_up: 7,
      nuke: 1,
      double_xp: 4,
      shock_chain: 3,
      fireblast: 2,
      reflex_boost: 5,
      shield: 6,
      freeze: 8,
      medkit: 14,
      speed: 9,
      fire_bullets: 11,
    },
  },
  {
    key: 'ui-wicons-grid2x1',
    path: 'assets/crimson/ui/ui_wicons.png',
    frameWidth: 64,
    frameHeight: 32,
  },
];

export const PROJECTILE_FRAMES: Record<WeaponId, number> = {
  pistol: 0,
  assault_rifle: 0,
  shotgun: 1,
  sawed_off_shotgun: 1,
  submachine_gun: 2,
  gauss_gun: 0,
  mean_minigun: 0,
  flamethrower: 2,
  plasma_rifle: 0,
  multi_plasma: 0,
  plasma_minigun: 0,
  rocket_launcher: 1,
  seeker_rockets: 1,
  plasma_shotgun: 0,
  blow_torch: 2,
  hr_flamer: 2,
  mini_rocket_swarmers: 1,
  rocket_minigun: 1,
  pulse_gun: 0,
  jackhammer: 1,
  ion_rifle: 0,
  ion_minigun: 0,
  ion_cannon: 0,
  shrinkifier_5k: 0,
  blade_gun: 0,
  spider_plasma: 0,
  evil_scythe: 0,
  plasma_cannon: 0,
  splitter_gun: 0,
  gauss_shotgun: 0,
  ion_shotgun: 1,
  flameburst: 0,
  raygun: 0,
  unknown_34: 0,
  unknown_35: 0,
  unknown_36: 0,
  unknown_37: 0,
  unknown_38: 0,
  unknown_39: 0,
  unknown_40: 0,
  plague_sphreader_gun: 0,
  bubblegun: 0,
  rainbow_gun: 0,
  grim_weapon: 0,
  fire_bullets: 0,
  unknown_46: 0,
  unknown_47: 0,
  unknown_48: 0,
  unknown_49: 0,
  transmutator: 0,
  blaster_r_300: 0,
  lighting_rifle: 0,
  nuke_launcher: 0,
};

export const BONUS_FRAMES: Record<BonusId, number> = {
  points: 12,
  energizer: 10,
  weapon: 1,
  weapon_power_up: 7,
  nuke: 1,
  double_xp: 4,
  shock_chain: 3,
  fireblast: 2,
  reflex_boost: 5,
  shield: 6,
  freeze: 8,
  medkit: 14,
  speed: 9,
  fire_bullets: 11,
};

export const WEAPON_FRAMES: Record<string, number> = {
  pistol: 0,
  revolver: 0,
  shotgun: 1,
  smg: 2,
  burst_rifle: 3,
  rifle: 3,
  sniper: 3,
  flamethrower: 2,
  plasma: 4,
  railgun: 4,
  rocket: 1,
  laser: 4,
};
