// Auto-generated by src/tools/gen_perks_catalog.ts
// DO NOT EDIT MANUALLY
// Generated at: 2026-02-05T14:49:30.124Z
// Source: ref/crimson-master/docs/perk-id-map.md

export type PerkRefId = number;

export type PerkId =
  | 'antiperk'
  | 'bloody_mess_quick_learner'
  | 'sharpshooter'
  | 'fastloader'
  | 'lean_mean_exp_machine'
  | 'long_distance_runner'
  | 'pyrokinetic'
  | 'instant_winner'
  | 'grim_deal'
  | 'alternate_weapon'
  | 'plaguebearer'
  | 'evil_eyes'
  | 'ammo_maniac'
  | 'radioactive'
  | 'fastshot'
  | 'fatal_lottery'
  | 'random_weapon'
  | 'mr_melee'
  | 'anxious_loader'
  | 'final_revenge'
  | 'telekinetic'
  | 'perk_expert'
  | 'unstoppable'
  | 'regression_bullets'
  | 'infernal_contract'
  | 'poison_bullets'
  | 'dodger'
  | 'bonus_magnet'
  | 'uranium_filled_bullets'
  | 'doctor'
  | 'monster_vision'
  | 'hot_tempered'
  | 'bonus_economist'
  | 'thick_skinned'
  | 'barrel_greaser'
  | 'ammunition_within'
  | 'veins_of_poison'
  | 'toxic_avenger'
  | 'regeneration'
  | 'pyromaniac'
  | 'ninja'
  | 'highlander'
  | 'jinxed'
  | 'perk_master'
  | 'reflex_boosted'
  | 'greater_regeneration'
  | 'breathing_room'
  | 'death_clock'
  | 'my_favourite_weapon'
  | 'bandage'
  | 'angry_reloader'
  | 'ion_gun_master'
  | 'stationary_reloader'
  | 'man_bomb'
  | 'fire_caugh'
  | 'living_fortress'
  | 'tough_reloader'
  | 'lifeline_50_50';

export interface PerkDef {
  id: PerkId;
  refId: PerkRefId;
  name: string;
  description: string;
  maxStacks: number;
  rarity: 'common' | 'uncommon' | 'rare' | 'legendary';
  prereq?: PerkId;
  tags?: string[];
}

export const PERKS: PerkDef[] = [
  {
    id: 'antiperk',
    refId: 0,
    name: "AntiPerk",
    description: "You shouldn't be seeing this..",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'bloody_mess_quick_learner',
    refId: 1,
    name: "Bloody Mess / Quick Learner",
    description: "More the merrier. More blood guarantees a 30% better experience. You spill more blood and gain more experience points. / You learn things faster than a regular Joe from now on gaining 30% more experience points from everything you do.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'sharpshooter',
    refId: 2,
    name: "Sharpshooter",
    description: "Miraculously your aiming improves drastically, but you take a little bit more time on actually firing the gun. If you order now, you also get a fancy LASER SIGHT without ANY charge!",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'fastloader',
    refId: 3,
    name: "Fastloader",
    description: "Man, you sure know how to load a gun.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'lean_mean_exp_machine',
    refId: 4,
    name: "Lean Mean Exp Machine",
    description: "Why kill for experience when you can make some of your own for free! With this perk the experience just keeps flowing in at a constant rate.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'long_distance_runner',
    refId: 5,
    name: "Long Distance Runner",
    description: "You move like a train that has feet and runs. You just need a little time to warm up. In other words you'll move faster the longer you run without stopping.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'pyrokinetic',
    refId: 6,
    name: "Pyrokinetic",
    description: "You see flames everywhere. Bare aiming at creatures causes them to heat up.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'instant_winner',
    refId: 7,
    name: "Instant Winner",
    description: "2500 experience points. Right away. Take it or leave it.",
    maxStacks: 99,
    rarity: 'common',
  tags: ['stackable'],
  },
  {
    id: 'grim_deal',
    refId: 8,
    name: "Grim Deal",
    description: "I'll make you a deal: I'll give you 18% more experience points, and you'll give me your life. So you'll die but score higher. Ponder that one for a sec.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'alternate_weapon',
    refId: 9,
    name: "Alternate Weapon",
    description: "Ever fancied about having two weapons available for use? This might be your lucky day; with this perk you'll get an extra weapon slot for another gun! Carrying around two guns slows you down slightly though. (You can switch the weapon slots with RELOAD key)",
    maxStacks: 1,
    rarity: 'uncommon',
  tags: ['mode_3_only'],
  },
  {
    id: 'plaguebearer',
    refId: 10,
    name: "Plaguebearer",
    description: "You carry a horrible disease. Good for you: you are immune. Bad for them: it is contagious! (Monsters become resistant over time though.)",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'evil_eyes',
    refId: 11,
    name: "Evil Eyes",
    description: "No living (nor dead) can resist the hypnotic power of your eyes: monsters freeze still as you look at them!",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'ammo_maniac',
    refId: 12,
    name: "Ammo Maniac",
    description: "You squeeze and you push and you pack your clips with about 20% more ammo than a regular fellow. They call you Ammo Maniac with a deep respect in their voices.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'radioactive',
    refId: 13,
    name: "Radioactive",
    description: "You are the Radioactive-man; you have that healthy green glow around you! Others don't like it though, it makes them sick and nauseous whenever near you. It does affect your social life a bit.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'fastshot',
    refId: 14,
    name: "Fastshot",
    description: "Funny how you make your gun spit bullets faster than the next guy. Even the most professional of engineers are astonished.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'fatal_lottery',
    refId: 15,
    name: "Fatal Lottery",
    description: "Fifty-fifty chance of dying OR gaining 10k experience points. Place your bets. Interested, anyone?",
    maxStacks: 99,
    rarity: 'common',
  tags: ['stackable'],
  },
  {
    id: 'random_weapon',
    refId: 16,
    name: "Random Weapon",
    description: "Here, have this weapon. No questions asked.",
    maxStacks: 99,
    rarity: 'common',
  tags: ['mode_3_only', 'stackable'],
  },
  {
    id: 'mr_melee',
    refId: 17,
    name: "Mr. Melee",
    description: "You master the art of melee fighting. You don't just stand still when monsters come near -- you hit back. Hard.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'anxious_loader',
    refId: 18,
    name: "Anxious Loader",
    description: "When you can't stand waiting your gun to be reloaded you can speed up the process by clicking your FIRE button repeatedly as fast as you can.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'final_revenge',
    refId: 19,
    name: "Final Revenge",
    description: "Pick this and you'll get your revenge. It's a promise.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'telekinetic',
    refId: 20,
    name: "Telekinetic",
    description: "Picking up bonuses has never been so easy and FUN. You can pick up bonuses simply by aiming at them for a while. Ingenious.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'perk_expert',
    refId: 21,
    name: "Perk Expert",
    description: "You sure know how to pick a perk -- most people just don't see that extra perk laying around. This gives you the opportunity to pick the freshest and shiniest perks from the top.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'unstoppable',
    refId: 22,
    name: "Unstoppable",
    description: "Monsters can't slow you down with their nasty scratches and bites. It still hurts but you simply ignore the pain.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'regression_bullets',
    refId: 23,
    name: "Regression Bullets",
    description: "Attempt to shoot with an empty clip leads to a severe loss of experience. But hey, whatever makes them go down, right?",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'infernal_contract',
    refId: 24,
    name: "Infernal Contract",
    description: "In exchange for your soul, a dark stranger is offering you three (3) new perks. To collect his part of the bargain soon enough, your health is reduced to a near-death status. Just sign down here below this pentagram..",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'poison_bullets',
    refId: 25,
    name: "Poison Bullets",
    description: "You tend to explicitly treat each of your bullets with rat poison. You do it for good luck, but it seems to have other side effects too.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'dodger',
    refId: 26,
    name: "Dodger",
    description: "It seems so stupid just to take the hits. Each time a monster attacks you you have a chance to dodge the attack.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'bonus_magnet',
    refId: 27,
    name: "Bonus Magnet",
    description: "You somehow seem to lure all kinds of bonuses to appear around you more often.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'uranium_filled_bullets',
    refId: 28,
    name: "Uranium Filled Bullets",
    description: "Your bullets have a nice creamy uranium filling. Yummy. Now that's gotta hurt the monsters more, right?",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'doctor',
    refId: 29,
    name: "Doctor",
    description: "With a single glance you can tell the medical condition of, well, anything. Also, being a doctor, you know exactly what hurts the most enabling you to do slightly more damage with your attacks.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'monster_vision',
    refId: 30,
    name: "Monster Vision",
    description: "With your newly enhanced senses you can see all bad energy VERY clearly. That's got to be enough.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'hot_tempered',
    refId: 31,
    name: "Hot Tempered",
    description: "It literally boils inside you. That's exactly why you need to let it out once in a while, unfortunately for those near you.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'bonus_economist',
    refId: 32,
    name: "Bonus Economist",
    description: "Your bonus power-ups last 50% longer than they normally would.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'thick_skinned',
    refId: 33,
    name: "Thick Skinned",
    description: "Trade 1/3 of your health for only receiving 2/3rds damage on attacks.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'barrel_greaser',
    refId: 34,
    name: "Barrel Greaser",
    description: "After studying a lot of physics and friction you've come up with a way to make your bullets fly faster. More speed, more damage.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'ammunition_within',
    refId: 35,
    name: "Ammunition Within",
    description: "Empty clip doesn't prevent you from shooting with a weapon; instead the ammunition is drawn from your health while you are reloading.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'veins_of_poison',
    refId: 36,
    name: "Veins of Poison",
    description: "A strong poison runs through your veins. Monsters taking a bite of you are eventually to experience an agonizing death.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'toxic_avenger',
    refId: 37,
    name: "Toxic Avenger",
    description: "You started out just by being poisonous. The next logical step for you is to become highly toxic -- the ULTIMATE TOXIC AVENGER. Most monsters touching you will just drop dead within seconds!",
    maxStacks: 1,
    rarity: 'rare',
  prereq: 'veins_of_poison',
  },
  {
    id: 'regeneration',
    refId: 38,
    name: "Regeneration",
    description: "Your health replenishes but very slowly. What more there is to say?",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'pyromaniac',
    refId: 39,
    name: "Pyromaniac",
    description: "You just enjoy using fire as your Tool of Destruction and you're good at it too; your fire based weapons do a lot more damage.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'ninja',
    refId: 40,
    name: "Ninja",
    description: "You've taken your dodging abilities to the next level; monsters have really hard time hitting you.",
    maxStacks: 1,
    rarity: 'rare',
  prereq: 'dodger',
  },
  {
    id: 'highlander',
    refId: 41,
    name: "Highlander",
    description: "You are immortal. Well, almost immortal. Instead of actually losing health on attacks you've got a 10% chance of just dropping dead whenever a monster attacks you. There really can be only one, you know.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'jinxed',
    refId: 42,
    name: "Jinxed",
    description: "Things happen near you. Strangest things. Creatures just drop dead and accidents happen. Beware.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'perk_master',
    refId: 43,
    name: "Perk Master",
    description: "Being the Perk Expert taught you a few things and now you are ready to take your training to the next level doubling the ability effect.",
    maxStacks: 1,
    rarity: 'rare',
  prereq: 'perk_expert',
  },
  {
    id: 'reflex_boosted',
    refId: 44,
    name: "Reflex Boosted",
    description: "To you the world seems to go on about 10% slower than to an average person. It can be rather irritating sometimes, but it does give you a chance to react better.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'greater_regeneration',
    refId: 45,
    name: "Greater Regeneration",
    description: "Your health replenishes faster than ever.",
    maxStacks: 1,
    rarity: 'rare',
  prereq: 'regeneration',
  },
  {
    id: 'breathing_room',
    refId: 46,
    name: "Breathing Room",
    description: "Trade 2/3rds of your health for the killing of every single creature on the screen. No, you don't get the experience.",
    maxStacks: 1,
    rarity: 'uncommon',
  tags: ['two_player_only'],
  },
  {
    id: 'death_clock',
    refId: 47,
    name: "Death Clock",
    description: "You die exactly in 30 seconds. You can't escape your destiny, but feel free to go on a spree. Tick, tock.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'my_favourite_weapon',
    refId: 48,
    name: "My Favourite Weapon",
    description: "You've grown very fond of your piece. You polish it all the time and talk nice to it, your precious. (+2 clip size, no more random weapon bonuses)",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'bandage',
    refId: 49,
    name: "Bandage",
    description: "Here, eat this bandage and you'll feel a lot better in no time. (restores up to 50% health)",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'angry_reloader',
    refId: 50,
    name: "Angry Reloader",
    description: "You hate it when you run out of shots. You HATE HATE HATE reloading your gun. Lucky for you, and strangely enough, your hate materializes as Mighty Balls of Fire. Or more like Quite Decent Balls of Fire, but it's still kinda neat, huh?",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'ion_gun_master',
    refId: 51,
    name: "Ion Gun Master",
    description: "You're good with ion weapons. You're so good that not only your shots do slightly more damage but your ion blast radius is also increased.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'stationary_reloader',
    refId: 52,
    name: "Stationary Reloader",
    description: "It's incredibly hard to reload your piece while moving around, you've noticed. In fact, realizing that, when you don't move a (leg) muscle you can reload the gun THREE TIMES FASTER!",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'man_bomb',
    refId: 53,
    name: "Man Bomb",
    description: "You have the ability to go boom for you are the MAN BOMB. Going boom requires a lot of concentration and standing completely still for a few seconds.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'fire_caugh',
    refId: 54,
    name: "Fire Caugh",
    description: "You have a fireball stuck in your throat. Repeatedly. Mind your manners.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'living_fortress',
    refId: 55,
    name: "Living Fortress",
    description: "It comes a time in each man's life when you'd just rather not move anymore. Being living fortress not moving comes with extra benefits as well. You do the more damage the longer you stand still.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'tough_reloader',
    refId: 56,
    name: "Tough Reloader",
    description: "Damage received during reloading a weapon is halved.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
  {
    id: 'lifeline_50_50',
    refId: 57,
    name: "Lifeline 50-50",
    description: "The computer removes half of the wrong monsters for you. You don't gain any experience.",
    maxStacks: 1,
    rarity: 'uncommon',
  },
];

export const PERK_BY_ID: Record<PerkId, PerkDef> = {
  'antiperk': PERKS.find((p) => p.id === 'antiperk')!,
  'bloody_mess_quick_learner': PERKS.find((p) => p.id === 'bloody_mess_quick_learner')!,
  'sharpshooter': PERKS.find((p) => p.id === 'sharpshooter')!,
  'fastloader': PERKS.find((p) => p.id === 'fastloader')!,
  'lean_mean_exp_machine': PERKS.find((p) => p.id === 'lean_mean_exp_machine')!,
  'long_distance_runner': PERKS.find((p) => p.id === 'long_distance_runner')!,
  'pyrokinetic': PERKS.find((p) => p.id === 'pyrokinetic')!,
  'instant_winner': PERKS.find((p) => p.id === 'instant_winner')!,
  'grim_deal': PERKS.find((p) => p.id === 'grim_deal')!,
  'alternate_weapon': PERKS.find((p) => p.id === 'alternate_weapon')!,
  'plaguebearer': PERKS.find((p) => p.id === 'plaguebearer')!,
  'evil_eyes': PERKS.find((p) => p.id === 'evil_eyes')!,
  'ammo_maniac': PERKS.find((p) => p.id === 'ammo_maniac')!,
  'radioactive': PERKS.find((p) => p.id === 'radioactive')!,
  'fastshot': PERKS.find((p) => p.id === 'fastshot')!,
  'fatal_lottery': PERKS.find((p) => p.id === 'fatal_lottery')!,
  'random_weapon': PERKS.find((p) => p.id === 'random_weapon')!,
  'mr_melee': PERKS.find((p) => p.id === 'mr_melee')!,
  'anxious_loader': PERKS.find((p) => p.id === 'anxious_loader')!,
  'final_revenge': PERKS.find((p) => p.id === 'final_revenge')!,
  'telekinetic': PERKS.find((p) => p.id === 'telekinetic')!,
  'perk_expert': PERKS.find((p) => p.id === 'perk_expert')!,
  'unstoppable': PERKS.find((p) => p.id === 'unstoppable')!,
  'regression_bullets': PERKS.find((p) => p.id === 'regression_bullets')!,
  'infernal_contract': PERKS.find((p) => p.id === 'infernal_contract')!,
  'poison_bullets': PERKS.find((p) => p.id === 'poison_bullets')!,
  'dodger': PERKS.find((p) => p.id === 'dodger')!,
  'bonus_magnet': PERKS.find((p) => p.id === 'bonus_magnet')!,
  'uranium_filled_bullets': PERKS.find((p) => p.id === 'uranium_filled_bullets')!,
  'doctor': PERKS.find((p) => p.id === 'doctor')!,
  'monster_vision': PERKS.find((p) => p.id === 'monster_vision')!,
  'hot_tempered': PERKS.find((p) => p.id === 'hot_tempered')!,
  'bonus_economist': PERKS.find((p) => p.id === 'bonus_economist')!,
  'thick_skinned': PERKS.find((p) => p.id === 'thick_skinned')!,
  'barrel_greaser': PERKS.find((p) => p.id === 'barrel_greaser')!,
  'ammunition_within': PERKS.find((p) => p.id === 'ammunition_within')!,
  'veins_of_poison': PERKS.find((p) => p.id === 'veins_of_poison')!,
  'toxic_avenger': PERKS.find((p) => p.id === 'toxic_avenger')!,
  'regeneration': PERKS.find((p) => p.id === 'regeneration')!,
  'pyromaniac': PERKS.find((p) => p.id === 'pyromaniac')!,
  'ninja': PERKS.find((p) => p.id === 'ninja')!,
  'highlander': PERKS.find((p) => p.id === 'highlander')!,
  'jinxed': PERKS.find((p) => p.id === 'jinxed')!,
  'perk_master': PERKS.find((p) => p.id === 'perk_master')!,
  'reflex_boosted': PERKS.find((p) => p.id === 'reflex_boosted')!,
  'greater_regeneration': PERKS.find((p) => p.id === 'greater_regeneration')!,
  'breathing_room': PERKS.find((p) => p.id === 'breathing_room')!,
  'death_clock': PERKS.find((p) => p.id === 'death_clock')!,
  'my_favourite_weapon': PERKS.find((p) => p.id === 'my_favourite_weapon')!,
  'bandage': PERKS.find((p) => p.id === 'bandage')!,
  'angry_reloader': PERKS.find((p) => p.id === 'angry_reloader')!,
  'ion_gun_master': PERKS.find((p) => p.id === 'ion_gun_master')!,
  'stationary_reloader': PERKS.find((p) => p.id === 'stationary_reloader')!,
  'man_bomb': PERKS.find((p) => p.id === 'man_bomb')!,
  'fire_caugh': PERKS.find((p) => p.id === 'fire_caugh')!,
  'living_fortress': PERKS.find((p) => p.id === 'living_fortress')!,
  'tough_reloader': PERKS.find((p) => p.id === 'tough_reloader')!,
  'lifeline_50_50': PERKS.find((p) => p.id === 'lifeline_50_50')!,
};

export function perkIdFromRefId(refId: number): PerkId | null {
  switch (refId) {
    case 0: return 'antiperk';
    case 1: return 'bloody_mess_quick_learner';
    case 2: return 'sharpshooter';
    case 3: return 'fastloader';
    case 4: return 'lean_mean_exp_machine';
    case 5: return 'long_distance_runner';
    case 6: return 'pyrokinetic';
    case 7: return 'instant_winner';
    case 8: return 'grim_deal';
    case 9: return 'alternate_weapon';
    case 10: return 'plaguebearer';
    case 11: return 'evil_eyes';
    case 12: return 'ammo_maniac';
    case 13: return 'radioactive';
    case 14: return 'fastshot';
    case 15: return 'fatal_lottery';
    case 16: return 'random_weapon';
    case 17: return 'mr_melee';
    case 18: return 'anxious_loader';
    case 19: return 'final_revenge';
    case 20: return 'telekinetic';
    case 21: return 'perk_expert';
    case 22: return 'unstoppable';
    case 23: return 'regression_bullets';
    case 24: return 'infernal_contract';
    case 25: return 'poison_bullets';
    case 26: return 'dodger';
    case 27: return 'bonus_magnet';
    case 28: return 'uranium_filled_bullets';
    case 29: return 'doctor';
    case 30: return 'monster_vision';
    case 31: return 'hot_tempered';
    case 32: return 'bonus_economist';
    case 33: return 'thick_skinned';
    case 34: return 'barrel_greaser';
    case 35: return 'ammunition_within';
    case 36: return 'veins_of_poison';
    case 37: return 'toxic_avenger';
    case 38: return 'regeneration';
    case 39: return 'pyromaniac';
    case 40: return 'ninja';
    case 41: return 'highlander';
    case 42: return 'jinxed';
    case 43: return 'perk_master';
    case 44: return 'reflex_boosted';
    case 45: return 'greater_regeneration';
    case 46: return 'breathing_room';
    case 47: return 'death_clock';
    case 48: return 'my_favourite_weapon';
    case 49: return 'bandage';
    case 50: return 'angry_reloader';
    case 51: return 'ion_gun_master';
    case 52: return 'stationary_reloader';
    case 53: return 'man_bomb';
    case 54: return 'fire_caugh';
    case 55: return 'living_fortress';
    case 56: return 'tough_reloader';
    case 57: return 'lifeline_50_50';
    default: return null;
  }
}
