import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { pathToFileURL } from 'url';
import { extractRefSpecsFromFile, type RefWeaponSpec } from './extract_ref_specs';

const OUTPUT_PATH = join('src', 'content', 'projectiles.generated.ts');
const REF_WEAPONS_PATH = join('ref', 'crimson-master', 'src', 'crimson', 'weapons.py');

interface RefProjectileInfo {
  typeId: number;
  name: string;
  weaponIds: number[];
}

const REF_PROJECTILE_TYPES: RefProjectileInfo[] = [
  { typeId: 0x01, name: 'PISTOL', weaponIds: [1, 7] },
  { typeId: 0x02, name: 'ASSAULT_RIFLE', weaponIds: [2] },
  { typeId: 0x03, name: 'SHOTGUN', weaponIds: [3, 4, 20] },
  { typeId: 0x05, name: 'SUBMACHINE_GUN', weaponIds: [5] },
  { typeId: 0x06, name: 'GAUSS_GUN', weaponIds: [6, 30] },
  { typeId: 0x09, name: 'PLASMA_RIFLE', weaponIds: [9, 10] },
  { typeId: 0x0B, name: 'PLASMA_MINIGUN', weaponIds: [11, 14] },
  { typeId: 0x13, name: 'PULSE_GUN', weaponIds: [19] },
  { typeId: 0x15, name: 'ION_RIFLE', weaponIds: [21] },
  { typeId: 0x16, name: 'ION_MINIGUN', weaponIds: [22, 31] },
  { typeId: 0x17, name: 'ION_CANNON', weaponIds: [23] },
  { typeId: 0x18, name: 'SHRINKIFIER', weaponIds: [24] },
  { typeId: 0x19, name: 'BLADE_GUN', weaponIds: [25] },
  { typeId: 0x1A, name: 'SPIDER_PLASMA', weaponIds: [26] },
  { typeId: 0x1C, name: 'PLASMA_CANNON', weaponIds: [28] },
  { typeId: 0x1D, name: 'SPLITTER_GUN', weaponIds: [29] },
  { typeId: 0x29, name: 'PLAGUE_SPREADER', weaponIds: [41] },
  { typeId: 0x2B, name: 'RAINBOW_GUN', weaponIds: [43] },
  { typeId: 0x2D, name: 'FIRE_BULLETS', weaponIds: [45] },
];

interface ProjectileSpec {
  typeId: number;
  name: string;
  speed: number;
  lifeSeconds: number;
  radius: number;
  baseDamageMeta: number | null;
  explosionRadius?: number;
  explosionDamage?: number;
  damagePool?: number;
}

function getProjectileSpec(
  refInfo: RefProjectileInfo,
  weaponSpecs: RefWeaponSpec[],
): ProjectileSpec {
  const weaponId = refInfo.weaponIds[0];
  const weapon = weaponSpecs.find((w) => w.weapon_id === weaponId);
  const baseDamageMeta = weapon?.projectile_meta ?? null;

  let radius = 1.0;
  let damagePool: number | undefined;

  switch (refInfo.typeId) {
    case 0x13:
    case 0x15:
    case 0x16:
    case 0x17:
      radius = 1.0;
      break;
    case 0x1C:
      radius = 1.0;
      break;
    default:
      radius = 1.0;
      break;
  }

  switch (refInfo.typeId) {
    case 0x06:
      damagePool = 300;
      break;
    case 0x2D:
      damagePool = 240;
      break;
    case 0x19:
      damagePool = 50;
      break;
    default:
      damagePool = 1;
      break;
  }

  return {
    typeId: refInfo.typeId,
    name: refInfo.name,
    speed: 20,
    lifeSeconds: 1.0,
    radius,
    baseDamageMeta,
    damagePool,
  };
}

function generateProjectileId(spec: ProjectileSpec): string {
  return spec.name.toLowerCase();
}

function generateProjectileIds(specs: ProjectileSpec[]): string {
  const ids = specs.map((s) => `'${generateProjectileId(s)}'`);
  return ids.join('\n  | ');
}

function formatNumber(value: number | null | undefined): string {
  if (value === null || value === undefined) return 'null';
  return String(value);
}

function generateProjectileDefs(specs: ProjectileSpec[]): string {
  const defs = specs.map((spec) => {
    const id = generateProjectileId(spec);
    return `  {
    typeId: ${spec.typeId},
    id: '${id}',
    name: '${spec.name}',
    speed: ${spec.speed},
    lifeSeconds: ${spec.lifeSeconds},
    radius: ${spec.radius},
    baseDamageMeta: ${formatNumber(spec.baseDamageMeta)},
    damagePool: ${formatNumber(spec.damagePool)},
  }`;
  });

  return defs.join(',\n');
}

function generateProjectileById(specs: ProjectileSpec[]): string {
  const entries = specs.map((spec) => {
    const id = generateProjectileId(spec);
    return `  '${id}': PROJECTILES.find(p => p.id === '${id}')!,`;
  });

  return entries.join('\n');
}

function generateProjectileByTypeId(specs: ProjectileSpec[]): string {
  const entries = specs.map((spec) => {
    const id = generateProjectileId(spec);
    return `  [${spec.typeId}]: '${id}',`;
  });

  return `export const PROJECTILE_BY_TYPE_ID: Record<number, ProjectileId> = {
${entries.join('\n')}
};`;
}

function generateFile(specs: ProjectileSpec[]): string {
  const projectileIds = generateProjectileIds(specs);
  const projectileDefs = generateProjectileDefs(specs);
  const projectileById = generateProjectileById(specs);
  const projectileByTypeId = generateProjectileByTypeId(specs);
  const timestamp = new Date().toISOString();

  return `// Auto-generated by src/tools/gen_projectile_catalog.ts
// DO NOT EDIT MANUALLY
// Generated at: ${timestamp}
// Source: ${REF_WEAPONS_PATH}

export type ProjectileId =
  | ${projectileIds};

export interface ProjectileDef {
  typeId: number;
  id: ProjectileId;
  name: string;
  speed: number;
  lifeSeconds: number;
  radius: number;
  baseDamageMeta: number | null;
  damagePool: number | null;
}

export const PROJECTILES: ProjectileDef[] = [
${projectileDefs},
];

export const PROJECTILE_BY_ID: Record<ProjectileId, ProjectileDef> = {
${projectileById}
};

${projectileByTypeId}
`;
}

export function checkMode(): boolean {
  return process.argv.includes('--check');
}

function normalizeGenerated(content: string): string {
  return content.replace(/\/\/ Generated at: [^\n]+\n/, '');
}

export function runGenerator(outputPath = OUTPUT_PATH, refPath = REF_WEAPONS_PATH): void {
  const { weapon_table: weaponSpecs } = extractRefSpecsFromFile(refPath);
  const specs = REF_PROJECTILE_TYPES.map((refInfo) => getProjectileSpec(refInfo, weaponSpecs));
  const generated = generateFile(specs);

  if (checkMode()) {
    if (!existsSync(outputPath)) {
      console.error(`Generated file does not exist: ${outputPath}`);
      process.exit(1);
    }

    const existing = readFileSync(outputPath, 'utf-8');
    if (normalizeGenerated(generated) !== normalizeGenerated(existing)) {
      console.error(`Generated file is out of sync. Run: npm run tools:gen-projectiles`);
      process.exit(1);
    }

    console.log(`✓ Generated file is up to date: ${outputPath}`);
    return;
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, generated, 'utf-8');
  console.log(`✓ Generated ${specs.length} projectiles to ${outputPath}`);
}

const currentFileUrl = pathToFileURL(process.argv[1] || '').href;
if (import.meta.url === currentFileUrl) {
  runGenerator();
}
